version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/cyfuture
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=30d
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL}
    restart: always
    volumes:
      - uploads:/app/backend/uploads

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data:
  uploads:
