export const ADMIN_DASHBOARD_REQUEST = 'ADMIN_DASHBOARD_REQUEST';
export const ADMIN_DASHBOARD_SUCCESS = 'ADMIN_DASHBOARD_SUCCESS';
export const ADMIN_DASHBOARD_FAIL = 'ADMIN_DASHBOARD_FAIL';

export const ADMIN_JOBS_REQUEST = 'ADMIN_JOBS_REQUEST';
export const ADMIN_JOBS_SUCCESS = 'ADMIN_JOBS_SUCCESS';
export const ADMIN_JOBS_FAIL = 'ADMIN_JOBS_FAIL';

export const ADMIN_COMPANY_PROFILE_UPDATE_REQUEST = 'ADMIN_COMPANY_PROFILE_UPDATE_REQUEST';
export const ADMIN_COMPANY_PROFILE_UPDATE_SUCCESS = 'ADMIN_COMPANY_PROFILE_UPDATE_SUCCESS';
export const ADMIN_COMPANY_PROFILE_UPDATE_FAIL = 'ADMIN_COMPANY_PROFILE_UPDATE_FAIL';
export const ADMIN_COMPANY_PROFILE_UPDATE_RESET = 'ADMIN_COMPANY_PROFILE_UPDATE_RESET';