export const RESUME_UPLOAD_REQUEST = 'RESUME_UPLOAD_REQUEST';
export const RESUME_UPLOAD_SUCCESS = 'RESUME_UPLOAD_SUCCESS';
export const RESUME_UPLOAD_FAIL = 'RESUME_UPLOAD_FAIL';
export const RESUME_UPLOAD_RESET = 'RESUME_UPLOAD_RESET';

export const RESUME_DETAILS_REQUEST = 'RESUME_DETAILS_REQUEST';
export const RESUME_DETAILS_SUCCESS = 'RESUME_DETAILS_SUCCESS';
export const RESUME_DETAILS_FAIL = 'RESUME_DETAILS_FAIL';

export const RESUME_CHATBOT_RESPONSE_REQUEST = 'RESUME_CHATBOT_RESPONSE_REQUEST';
export const RESUME_CHATBOT_RESPONSE_SUCCESS = 'RESUME_CHATBOT_RESPONSE_SUCCESS';
export const RESUME_CHATBOT_RESPONSE_FAIL = 'RESUME_CHATBOT_RESPONSE_FAIL';
export const RESUME_CHATBOT_RESPONSE_RESET = 'RESUME_CHATBOT_RESPONSE_RESET';