// Auth Constants
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGOUT = 'USER_LOGOUT';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

export const USER_UPDATE_PROFILE_REQUEST = 'USER_UPDATE_PROFILE_REQUEST';
export const USER_UPDATE_PROFILE_SUCCESS = 'USER_UPDATE_PROFILE_SUCCESS';
export const USER_UPDATE_PROFILE_FAIL = 'USER_UPDATE_PROFILE_FAIL';
export const USER_UPDATE_PROFILE_RESET = 'USER_UPDATE_PROFILE_RESET';

// Job Constants
export const JOB_LIST_REQUEST = 'JOB_LIST_REQUEST';
export const JOB_LIST_SUCCESS = 'JOB_LIST_SUCCESS';
export const JOB_LIST_FAIL = 'JOB_LIST_FAIL';

export const JOB_DETAILS_REQUEST = 'JOB_DETAILS_REQUEST';
export const JOB_DETAILS_SUCCESS = 'JOB_DETAILS_SUCCESS';
export const JOB_DETAILS_FAIL = 'JOB_DETAILS_FAIL';

export const JOB_CREATE_REQUEST = 'JOB_CREATE_REQUEST';
export const JOB_CREATE_SUCCESS = 'JOB_CREATE_SUCCESS';
export const JOB_CREATE_FAIL = 'JOB_CREATE_FAIL';
export const JOB_CREATE_RESET = 'JOB_CREATE_RESET';

export const JOB_UPDATE_REQUEST = 'JOB_UPDATE_REQUEST';
export const JOB_UPDATE_SUCCESS = 'JOB_UPDATE_SUCCESS';
export const JOB_UPDATE_FAIL = 'JOB_UPDATE_FAIL';
export const JOB_UPDATE_RESET = 'JOB_UPDATE_RESET';

export const JOB_DELETE_REQUEST = 'JOB_DELETE_REQUEST';
export const JOB_DELETE_SUCCESS = 'JOB_DELETE_SUCCESS';
export const JOB_DELETE_FAIL = 'JOB_DELETE_FAIL';

export const EMPLOYER_JOBS_REQUEST = 'EMPLOYER_JOBS_REQUEST';
export const EMPLOYER_JOBS_SUCCESS = 'EMPLOYER_JOBS_SUCCESS';
export const EMPLOYER_JOBS_FAIL = 'EMPLOYER_JOBS_FAIL';

export const TOP_JOBS_REQUEST = 'TOP_JOBS_REQUEST';
export const TOP_JOBS_SUCCESS = 'TOP_JOBS_SUCCESS';
export const TOP_JOBS_FAIL = 'TOP_JOBS_FAIL';

export const SAVE_JOB_REQUEST = 'SAVE_JOB_REQUEST';
export const SAVE_JOB_SUCCESS = 'SAVE_JOB_SUCCESS';
export const SAVE_JOB_FAIL = 'SAVE_JOB_FAIL';

export const UNSAVE_JOB_REQUEST = 'UNSAVE_JOB_REQUEST';
export const UNSAVE_JOB_SUCCESS = 'UNSAVE_JOB_SUCCESS';
export const UNSAVE_JOB_FAIL = 'UNSAVE_JOB_FAIL';

export const SAVED_JOBS_REQUEST = 'SAVED_JOBS_REQUEST';
export const SAVED_JOBS_SUCCESS = 'SAVED_JOBS_SUCCESS';
export const SAVED_JOBS_FAIL = 'SAVED_JOBS_FAIL';

// Application Constants
export const APPLICATION_CREATE_REQUEST = 'APPLICATION_CREATE_REQUEST';
export const APPLICATION_CREATE_SUCCESS = 'APPLICATION_CREATE_SUCCESS';
export const APPLICATION_CREATE_FAIL = 'APPLICATION_CREATE_FAIL';
export const APPLICATION_CREATE_RESET = 'APPLICATION_CREATE_RESET';

export const JOB_APPLICATIONS_REQUEST = 'JOB_APPLICATIONS_REQUEST';
export const JOB_APPLICATIONS_SUCCESS = 'JOB_APPLICATIONS_SUCCESS';
export const JOB_APPLICATIONS_FAIL = 'JOB_APPLICATIONS_FAIL';

export const USER_APPLICATIONS_REQUEST = 'USER_APPLICATIONS_REQUEST';
export const USER_APPLICATIONS_SUCCESS = 'USER_APPLICATIONS_SUCCESS';
export const USER_APPLICATIONS_FAIL = 'USER_APPLICATIONS_FAIL';

export const APPLICATION_DETAILS_REQUEST = 'APPLICATION_DETAILS_REQUEST';
export const APPLICATION_DETAILS_SUCCESS = 'APPLICATION_DETAILS_SUCCESS';
export const APPLICATION_DETAILS_FAIL = 'APPLICATION_DETAILS_FAIL';

export const APPLICATION_UPDATE_REQUEST = 'APPLICATION_UPDATE_REQUEST';
export const APPLICATION_UPDATE_SUCCESS = 'APPLICATION_UPDATE_SUCCESS';
export const APPLICATION_UPDATE_FAIL = 'APPLICATION_UPDATE_FAIL';
export const APPLICATION_UPDATE_RESET = 'APPLICATION_UPDATE_RESET';

export const APPLICATION_DELETE_REQUEST = 'APPLICATION_DELETE_REQUEST';
export const APPLICATION_DELETE_SUCCESS = 'APPLICATION_DELETE_SUCCESS';
export const APPLICATION_DELETE_FAIL = 'APPLICATION_DELETE_FAIL';

// Resume Constants
export const RESUME_UPLOAD_REQUEST = 'RESUME_UPLOAD_REQUEST';
export const RESUME_UPLOAD_SUCCESS = 'RESUME_UPLOAD_SUCCESS';
export const RESUME_UPLOAD_FAIL = 'RESUME_UPLOAD_FAIL';
export const RESUME_UPLOAD_RESET = 'RESUME_UPLOAD_RESET';

export const USER_RESUME_REQUEST = 'USER_RESUME_REQUEST';
export const USER_RESUME_SUCCESS = 'USER_RESUME_SUCCESS';
export const USER_RESUME_FAIL = 'USER_RESUME_FAIL';

export const RESUME_DELETE_REQUEST = 'RESUME_DELETE_REQUEST';
export const RESUME_DELETE_SUCCESS = 'RESUME_DELETE_SUCCESS';
export const RESUME_DELETE_FAIL = 'RESUME_DELETE_FAIL';

// Resume Fetch (add for reducer compatibility)
export const RESUME_FETCH_REQUEST = 'RESUME_FETCH_REQUEST';
export const RESUME_FETCH_SUCCESS = 'RESUME_FETCH_SUCCESS';
export const RESUME_FETCH_FAIL = 'RESUME_FETCH_FAIL';

// Chat Constants
export const CHAT_GET_REQUEST = 'CHAT_GET_REQUEST';
export const CHAT_GET_SUCCESS = 'CHAT_GET_SUCCESS';
export const CHAT_GET_FAIL = 'CHAT_GET_FAIL';

export const CHAT_SEND_REQUEST = 'CHAT_SEND_REQUEST';
export const CHAT_SEND_SUCCESS = 'CHAT_SEND_SUCCESS';
export const CHAT_SEND_FAIL = 'CHAT_SEND_FAIL';

// Chat Fetch (add for reducer compatibility)
export const CHAT_FETCH_REQUEST = 'CHAT_FETCH_REQUEST';
export const CHAT_FETCH_SUCCESS = 'CHAT_FETCH_SUCCESS';
export const CHAT_FETCH_FAIL = 'CHAT_FETCH_FAIL';

// Analytics Constants
export const EMPLOYER_ANALYTICS_REQUEST = 'EMPLOYER_ANALYTICS_REQUEST';
export const EMPLOYER_ANALYTICS_SUCCESS = 'EMPLOYER_ANALYTICS_SUCCESS';
export const EMPLOYER_ANALYTICS_FAIL = 'EMPLOYER_ANALYTICS_FAIL';

export const ADMIN_ANALYTICS_REQUEST = 'ADMIN_ANALYTICS_REQUEST';
export const ADMIN_ANALYTICS_SUCCESS = 'ADMIN_ANALYTICS_SUCCESS';
export const ADMIN_ANALYTICS_FAIL = 'ADMIN_ANALYTICS_FAIL';

// Analytics Fetch (add for reducer compatibility)
export const ANALYTICS_FETCH_REQUEST = 'ANALYTICS_FETCH_REQUEST';
export const ANALYTICS_FETCH_SUCCESS = 'ANALYTICS_FETCH_SUCCESS';
export const ANALYTICS_FETCH_FAIL = 'ANALYTICS_FETCH_FAIL';

// UI Constants
export const SET_SIDEBAR_OPEN = 'SET_SIDEBAR_OPEN';
export const SET_DARK_MODE = 'SET_DARK_MODE';
export const SET_LANGUAGE = 'SET_LANGUAGE';